
build:
	@spm build

deploy:
	@rm -rf ../../modules/easyhin/common
	@mkdir  ../../modules/easyhin/common
	@mkdir  ../../modules/easyhin/common/1.0.0
	@cp     dist/*.* ../../modules/easyhin/common/1.0.0
	@echo
	@echo   " deploy to ../../modules/easyhin/common/1.0.0"
	@echo
